version: "3"
services:
  mongodb:
    image: mongo:4.4
    container_name: "db-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - /home/desktop/volume/utils:/data/db
    ports:
      - 27017:27017
    restart: always
